image: node:10.13.0

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test
  - publish
  - post-publish

lint:
  stage: test
  except:
    - master
  script:
    - npm install
    - npm run lint

lint:code-formatter:
  stage: test
  except:
    - master
  script:
    - npm install
    - npm run format:check

publish-docker:
  stage: publish
  image: docker
  only:
    - /^release/.*$/
  script:
    - apk add --update jq nodejs npm
    - npm install
    - npm run build
    - VERSION_TAG=$(jq -r .version package.json)
    - docker login ${CI_REGISTRY} -u gitlab-ci-token -p ${CI_BUILD_TOKEN}
    - docker pull ${CI_REGISTRY_IMAGE}:${VERSION_TAG} && echo "Tag ${VERSION_TAG} already exists" && exit 1 || true
    - docker build -t ${CI_REGISTRY_IMAGE}:latest -t ${CI_REGISTRY_IMAGE}:${VERSION_TAG}  .
    - docker push ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:${VERSION_TAG}
    - docker login -u hmajid2301 -p ${DOCKER_PASSWORD}
    - export IMAGE_NAME="hmajid2301/netlify-subdomain-manager"
    - docker build -t ${IMAGE_NAME}:latest -t ${IMAGE_NAME}:${VERSION_TAG}  .
    - docker push ${IMAGE_NAME}:latest
    - docker push ${IMAGE_NAME}:${VERSION_TAG}

publish:npm:
  stage: publish
  only:
    - /^release/.*$/
  script:
    - npm install
    - npm run build
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish --non-interactive

publish-readme:hub:
  stage: post-publish
  only:
    - /^release/.*$/
  image:
    name: registry.gitlab.com/hmajid2301/dockerhub-descriptions-updater
    entrypoint: [""]
  variables:
    DOCKERHUB_USERNAME: hmajid2301
    DOCKERHUB_PASSWORD: ${DOCKER_PASSWORD}
    DOCKERHUB_REPO_NAME: netlify-subdomain-manager
    README_FILEPATH: README.md
  script:
    - node /app/index.js
